version: '3.8'

services:
  piper-load-generator:
    profiles:
      - with-loader
    build:
      dockerfile: ./piper-load-generator/Dockerfile
    networks:
      - piper
    depends_on:
      - piper-backend
    environment:
      - PIPER_BACKEND_BASE_URL=http://piper-backend

  piper-backend:
    build:
      dockerfile: ./piper-backend/Dockerfile
    ports:
      - "2796:80"
    networks:
      - piper
    depends_on:
      - database
    environment:
      - PIPER_SERVER_PORT=80
      - SPRING_LIQUIBASE_CONTEXTS=test
      - PIPER_DB_USERNAME=piper
      - PIPER_DB_PASSWORD=piper
      - PIPER_DB_JDBC_URL=jdbc:postgresql://database:5432/piper

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: piper
      POSTGRES_PASSWORD: piper
      POSTGRES_DB: piper
    networks:
      - piper
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  piper:

volumes:
  db-data:
