################################################
# THIS FILE IS FOR DATABASE CONFIGURATION ONLY #
################################################

spring:
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    open-in-view: false
  datasource:
    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:50}
      minimum-idle: ${HIKARI_MIN_IDLE:10}
    username: ${PIPER_DB_USERNAME}
    password: ${PIPER_DB_PASSWORD}
    url: ${PIPER_DB_JDBC_URL}
